### ISSUE TITLE
6.3 Pointer arithmetic (not operable code in the ZIg 0.13.0

### ISSUE THREAD

**Issue by ypeskov** [pedropark99/zig-book#120]
Hi there,

I am reading the book and found the example in 6.3 "Pointer arithmetic"  is not working in the 0.13.0 version
```zig    
    const ar = [_]i32{ 1, 2, 3, 4 };
    var ptr = &ar;
    try stdout.print("{d}\n", .{ptr.*});
    ptr += 1;
    try stdout.print("{d}\n", .{ptr.*});
    ptr += 1;
    try stdout.print("{d}\n", .{ptr.*});
```

the errors:

> src/main.zig:28:9: error: incompatible types: '*const [4]i32' and 'comptime_int'
    ptr += 1;
    ~~~~^~~~
src/main.zig:28:5: note: type '*const [4]i32' here
    ptr += 1;
    ^~~
src/main.zig:28:12: note: type 'comptime_int' here
    ptr += 1;


I am just learnign Zig, so not sure which is correct, but with the help of ChatGPT got this version:
```zig    
    var ar = [_]i32{ 1, 2, 3, 4 };
    var ptr: [*]i32 = @as([*]i32, &ar);
    std.debug.print("{}\n", .{ptr[0]});
    ptr += 1;
    std.debug.print("{}\n", .{ptr[0]});
    ptr += 1;
    std.debug.print("{}\n", .{ptr[0]});
```

and it proposed the next text for this part:

> Pointer arithmetic is available in Zig and works similarly to C. When you have a pointer that points to an array, it usually points to the first element of that array. You can then use pointer arithmetic to traverse the array and access its elements.

> Notice in the example below that the ptr variable initially points to the first element of the array ar. By incrementing the pointer using simple pointer arithmetic, we can walk through the array and print each element.

> Explanation:
	•	var ptr: [*]i32 = &ar[0]; → Initializes a pointer to the first element of ar.
	•	ptr += 1; → Advances the pointer to the next element.
	•	ptr[0] → Accesses the element at the current pointer position.

**Comment by pedropark99** [comment]
Related to #110
